name: release
on:
  push:
    tags: ["v*"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: |
          test -n "$NPM_TOKEN"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          pnpm install
          pnpm build
          pnpm publish --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
